language: python
python:
  - "3.6"
# command to install dependencies 
install:
  - pip install -r requirements.txt
#  - pip install coveralls
# command to run tests
script: 
  - pytest src/csv2df --doctest-modules
#after_success:
#  - codecov
#  - coveralls
