language: python
python:
  - "3.6"
# command to install dependencies 
install:
  - pip install -r requirements.txt
# command to run tests
script: 
  - pytest src/kep --doctest-modules
#after_success:
#TODO: add codecov to requirements + add .cov to script + run locally + commit
  - codecov
