# https://docs.codecov.io/v4.3.6/docs/ignoring-paths
ignore:
  - "*/test_*.py"     # wildcards accepted
  - "tests/*"         # wildcards accepted
  - */usercase/*.py
  - tasks.py
  - src/manage.py 
  - src/kep/word2csv/word.py
